config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/jobs', to: 'jobs#index'
  get '/sign-up', to: 'users#new'
  post '/users', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  namespace :openings do

    get '/search', to: 'search#search_jobs'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
    validates :title, presence: true, length: {minimum: 2, maximum: 75}
    validates :company, presence: true, length: {minimum: 2, maximum: 75}

    def self.search(query)
        where('lower(title) LIKE :query OR lower(company) LIKE :query', query: "%#{query.downcase}%")
    end

end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :password_digest, presence: true
    has_secure_password
    password_requirements = /\A 
        (?=.{6,}) # At least 8 characters long
        (?=.*\d) # Contain at least one number
        (?=.*[a-z]) # Contain at least one lowercase letter
        (?=.*[A-Z]) # Contain at least one uppercase letter
        (?=.*[[:^alnum:]])
    /x
    validates :password, format: password_requirements 

    has_many :jobs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :redirect_if_guest 
  before_action :require_same_poster, only: [:destroy]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = helpers.current_user.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully posted." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    private

    def require_same_poster
      if helpers.current_user != @job.user_id
        flash[:notice] = "Action not authorized!"
        redirect_to job_url(@job)
      end
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :company, :salary, :location)
    end
end

app/controllers/openings/search_controller.rb
module Openings
    class SearchController < ApplicationController
        def search_jobs
            
            @jobs = Job.search(params[:query])
        
        end
    end
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  
    def jobs
    end
 
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create 
      @user = User.find_by(email: params[:email])
  
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Successfully logged in!"
      else 
        render :new, notice: "Invalid email or password"
      end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Successfully logged out"
        redirect_to root_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    before_action :set_user, only: %i[ show edit update destroy ]
    def new 
      @user = User.new
    end
  
    def create 
      @user = User.new(user_params)
      if @user.save 
        flash[:notice] = "You have successfully signed up!"
        redirect_to root_path
      else 
        flash[:notice] = "There was a problem signing you up. Please try again."
        render :new 
      end
    end
  
    def show  
    end
  
    private
    
    def user_params
      params.require(:user).permit(:email, :password)
    end
  
    def set_user 
      @user = User.find(params[:id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="job-form">
  <div>
    <center><h1><strong>New Job</strong></h1></center>
    <center><p><i>Complete the form below.</i></p></center>
  </div>
  
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>

</div>
<% end %>

app/views/jobs/_job.html.erb
  <p>
    <strong>Title:</strong>
    <%= job.title %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= job.company %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= job.salary %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= job.location %>
  </p>
</div>

<div id="<%= dom_id job %>">
  <% if job.user %>
    <div><i><strong>Posted by: </strong>
    <%= job.user.email %> </i></div>
  <% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<center><h1>Current Job Openings</h1></center>
<center><p>The following positions are currently available!</p></center>
<br><br>

<div id="jobs">
  <% @jobs.each do |job| %>
    <%= render job %>
    <p>
      <%= link_to "More details", job %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New job", new_job_path %>

app/views/jobs/new.html.erb
<%= render "form", job: @job %>

<br>

<div><center>
  <%= button_to "Back to jobs", jobs_path %>
</center></div>

app/views/jobs/search_jobs.html.erb
<h1>Search Jobs</h1>

<% @jobs.each do |job| %>
<h2><%= job.title %></h2>
<p><%= job.company %></p>
<p><%= job.salary %></p>
<p><%= job.location %></p>
<% end %> 

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <% if current_user == @job.user %>
    <%= link_to "Edit this job", edit_job_path(@job) %> |  
      <%= link_to "Delete this job", @job, method: :delete %>
  <% end %>
  <br><br>
  <%= button_to "Back to jobs", jobs_path %>
</div>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPostings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav'%> <%= yield %>
  </body>
</html>

app/views/openings/search/search_jobs.html.erb
<h1>Search Results</h1>
<p>Search results for <b><%= @search%></b></p>

<% @jobs.each do |job| %>
<h2><%= job.title %></h2>
<h3><%= job.company %></h3>
<p><b>Salary:</b> $<%= job.salary %> | <b>In-House/Remote:</b> <%= job.location %></p>
<button>Apply Now</button>
<hr>
<% end %>

app/views/pages/home.html.erb
<h1>Welcome!</h1>
<p>Kick start your career today.</p>


app/views/shared/_nav.html.erb
<div class="navbar"><ul>
  <li><%= link_to 'Home', root_path %></li>
  <% if logged_in? %>
     <li><%= link_to 'Job Openings', jobs_path %></li>
     <li><%= link_to 'My Jobs', user_path(current_user) %>
     <li><%= link_to 'Logout', logout_path, data: {'turbo-method': :delete} %></li>
  <% else %>
     <li><%= link_to 'Sign Up', sign_up_path %></li>
     <li><%= link_to 'Login', login_path %></li>
    <% end %>
    <li class="search">
    <%= form_with url: "/openings/search", method: :get do |form| %> <%= form.label :query, "Search:" %> 
    <%= form.text_field :query %> <%= form.submit "Go" %> <% end %>
    </li>
  </ul>
</div>

app/views/users/new.html.erb
<%= form_with(model: @user) do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email%>
  </div>
    <div>
    <%= form.label :password %>
    <%= form.password_field :password%>
  </div>
  <div>
    <%= form.submit "Sign Up"%>
  </div>
<% end %>